description: "A new Flutter project."
name: "hydro_demo"
version: "1.0.0+1"
dependencies: 
  cupertino_icons: "^0.1.2"
  flutter: 
    sdk: "flutter"
  hydro_sdk: 
    git: 
      ref: "0.0.1-nightly.20"
      url: "git://github.com/hydro-sdk/hydro-sdk.git"
  waveform: 
    git: 
      ref: "0.0.1-nightly.18"
      url: "git://github.com/hydro-sdk/waveform.git"
dev_dependencies: 
  flutter_test: 
    sdk: "flutter"
environment: 
  sdk: ">=2.1.0 <3.0.0"
flutter: 
  assets: 
    - "assets/hello-world.hc"
    - "assets/hello-world.hc.symbols"
  uses-material-design: true
